name: Feature request
description: Template for feature request
title: '[Feature request]: '
labels: enhancement
assignees: jan-tennert
body:
  - type: checkboxes
    id: latest-version
    attributes:
      label: General Info
      options:
        - label: I installed the latest version of SupaCompose
          required: true
        - label: I checked for similar feature requests
          required: true
  - type: textarea
    id: feature-request
    attributes:
      label: Feature request
      description: Please describe what you think should be added to SupaCompose
    validations:
      required: true
  - type: textarea
    id: usecase
    attributes:
      label: Usecase
      description: 'Please provide an usecase for your feature request '
    validations:
      required: true
