# Uncomment the next line to define a global platform for your project
platform :ios, '17.2'

target 'chatdemoios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for chatdemoios
  pod 'common', :path => '/Users/hieuvu/Projects/supabase-kt/demos/chat-demo-mpp/common/common.podspec'

end
