name: Build samples

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        sample: [
          'chat-demo-mpp',
          'file-upload',
          'multi-factor-auth'
        ]
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.0.1
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}
      - name: Build sample ${{ matrix.sample }}
        run: ./gradlew :sample:${{ matrix.sample }}:buildAll --stacktrace --configuration-cache